spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/transport?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    username: t_admin
    password: root
    hikari:
      maximum-pool-size: 10
  freemarker:
    expose-request-attributes: true



  flyway:
    enabled: true
    ignore-missing-migrations: true
    locations: classpath:/migration
    baseline-on-migrate: true
    baseline-description: Flyway Script
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
---

logging:
#  file:
#    name: /
  pattern:
#    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: INFO
    guru.springframework.controllers: INFO
    org.hibernate: INFO
